# Persistant Volume Clain (PVC), not to be used in statefulset
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sqlite-pvc
#   namespace: todo-app
# spec:
#   accessModes:
#     - ReadWriteOnce # here, 'Once' means volume can only be attached with one node at a time. Replacable with Many
#   resources:
#     requests:
#       storage: 1Gi

# Headless service: required for StatefulSet stable DNS indentity
apiVersion: v1
kind: Service
metadata:
  name: todo-app-headless
  namespace: todo-app
spec:
  clusterIP: None
  selector:
    app: todo-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080

# Application deployment -> Changed to StatefulSet from deployment
---
apiVersion: apps/v1
kind: StatefulSet #Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  serviceName: "todo-app-headless" # the name of the headless service name
  replicas: 3 # can be scaled upto more using kubectl cli
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      securityContext: # defining pod level security context
        runAsNonRoot: true       # Kubernetes rejects the pod if UID == 0
        runAsUser: 1000          # Must match the UID of 'app' user in the image
        runAsGroup: 1000         # Primary group for all processes
        fsGroup: 1000            # Ensures volume mounts (PVC) are owned by this GID
      containers:
        - name: todo-app
          image: todo-registry:5000/todo-app:latest # hsfassih/todo-app
          securityContext: # defining securitycontext at container level
            allowPrivilegeEscalation: false   # Prevents sudo, setuid binaries, etc.
            readOnlyRootFilesystem: true      # Makes / read-only
            capabilities:
              drop:
                - ALL                         # Drops all Linux kernel capabilities, defence in depth; removes capabilities like NET_BIND_SERVICE, CHOWN, etc. that are granted by default.
          imagePullPolicy: IfNotPresent # checks for local registry first. Change to Never if you used: k3d image import. Chnage to Always for dockerhub
          ports:
            - containerPort: 8080
          # logging: # added logging configuration
          #   driver: "json-file"
          #   options:
          #     max-size: "10m"
          #     max-file: "3"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: app-config          
          env:
            - name: secret_key
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: secret_key
            - name: algorithm
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: algorithm
            - name: access_token_expire_minutes
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: access_token_expire_minutes
            - name: database_url
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: database_url
            - name: redis_url
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: redis_url
            - name: DB_PASSWORD              # <-- ADD THIS (individual Secret key as env var)
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: db_password
          volumeMounts:
            - mountPath: /tmp
              name: tmp-dir
            - mountPath: /app/data
              name: sqlite-storage # name of volumeClaimTemplate
            - mountPath: /etc/app-config     # <-- ConfigMap mounted as files
              name: app-config-volume
              readOnly: true
            - mountPath: /etc/secrets        # <-- Secret mounted as files
              name: app-secret-volume
              readOnly: true
      volumes:
        - name: tmp-dir # This is required. When readOnlyRootFilesystem: true, /tmp becomes read-only too, without a writable /tmp, the app will crash on startup.
          emptyDir: {}  # emptyDir volumes are writable in-memory (or on-disk) scratch space per pod. They satisfy the write requirement for /tmp without loosening the root filesystem restriction.
        - name: app-config-volume
          configMap:
            name: app-config
        - name: app-secret-volume
          secret:
            secretName: todo-secret
  volumeClaimTemplates:
    - metadata:
        name: sqlite-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

# Application Cluster IP Service            
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

---
# Application NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: todo-app-nodeport
  namespace: todo-app
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080 # nodeport must be between 30000-32767

---
# Application LoadBalancer service
apiVersion: v1
kind: Service
metadata:
  name: todo-app-loadbalancer
  namespace: todo-app
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080