apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-todo-db
  namespace: todo-app
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    todouser:
      - superuser
      - createdb
  databases:
    tododb: todouser
  postgresql:
    version: "16"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi