"""Initial schema

Revision ID: 515a9705851d
Revises: 
Create Date: 2026-03-30 23:26:02.929029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515a9705851d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    # op.drop_table('task')
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('task',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('assigner', sa.VARCHAR(), nullable=False),
    # sa.Column('assignee', sa.VARCHAR(), nullable=False),
    # sa.Column('detail', sa.VARCHAR(), nullable=False),
    # sa.Column('task_status', sa.VARCHAR(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('user',
    # sa.Column('id', sa.INTEGER(), nullable=True),
    # sa.Column('full_name', sa.VARCHAR(), nullable=False),
    # sa.Column('username', sa.VARCHAR(), nullable=False),
    # sa.Column('hashed_pswrd', sa.VARCHAR(), nullable=False),
    # sa.Column('role', sa.VARCHAR(), nullable=False),
    # sa.PrimaryKeyConstraint('username'),
    # sa.UniqueConstraint('username')
    # )
    # ### end Alembic commands ###
