namespace: todo-dev
replicaCount: 1

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"

redis:
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"

ingress:
  appHost: api.dev.todo.local
  demoHost: demo.dev.todo.local

config:
  appEnv: "development"
  logLevel: "debug"

secret:
  secretKey: "dev-secret-key"
  algorithm: "HS256"                                          
  accessTokenExpireMinutes: "30"                              
  redisUrl: "redis://redis-service:6379"                     
  databaseUrl: "sqlite+aiosqlite:////app/data/todo_dev.db"
  dbPassword: "dev-db-password"                               