name: Deploy Lambda

on:
    push:
        branches: [main]
        paths:
            - "lambda/**"       # only when lambda code changes
            - "terraform/**"    # when terraform config changes

permissions:
    contents: read
    id-token: write     # required for OIDC auth (better approach over static keys w.r.t security)

jobs:
    deploy:
        name: Package & Deploy Lambda
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            # Authenticate to AWS with OIDC (instead of keys stored in secrets)
            -   name: Configure AWS credentials for OIDC
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
                    aws-region: us-east-1

            # Zip the contents of lambda/
            -   name: Package Lambda functions
                run: |
                    # Create temp build directories
                    mkdir -p build/getnewsfeed build/displaynews
                    
                    # Package getnewsfeed
                    pip install -r lambda/requirements.txt -t build/getnewsfeed/
                    cp lambda/getnewsfeed.py build/getnewsfeed/
                    cd build/getnewsfeed && zip -r ../../getnewsfeed.zip . && cd ../..
                    
                    # Package displaynews
                    pip install -r lambda/requirements.txt -t build/displaynews/
                    cp lambda/displaynews.py build/displaynews/
                    cd build/displaynews && zip -r ../../displaynews.zip . && cd ../..
                    
                    # Keep the original hello-lambda packaging
                    mkdir -p build/hello
                    pip install -r lambda/requirements.txt -t build/hello/
                    cp lambda/function1.py build/hello/
                    cd build/hello && zip -r ../../function.zip . && cd ../..
                    # Package sendnews (boto3 is built-in to Lambda runtime, no pip install needed)
                    mkdir -p build/sendnews
                    cp lambda/sendnews.py build/sendnews/
                    cd build/sendnews && zip -r ../../sendnews.zip . && cd ../...
            # Compute hash for functions
            -   name: Compute source hashes
                id: hashes
                run: |
                    HASH1=$(openssl dgst -sha256 -binary function.zip | openssl base64)
                    HASH2=$(openssl dgst -sha256 -binary getnewsfeed.zip | openssl base64)
                    HASH3=$(openssl dgst -sha256 -binary displaynews.zip | openssl base64)
                    HASH4=$(openssl dgst -sha256 -binary sendnews.zip | openssl base64)
                    echo "lambda=$HASH1" >> "$GITHUB_OUTPUT"
                    echo "getnewsfeed=$HASH2" >> "$GITHUB_OUTPUT"
                    echo "displaynews=$HASH3" >> "$GITHUB_OUTPUT"
                    echo "sendnews=$HASH4" >> "$GITHUB_OUTPUT"

            # Upload the package to S3 bucket
            -   name: Upload zip to S3
                run: |
                    aws s3 cp function.zip s3://hsfassih-todo-app/lambda/function.zip
                    aws s3 cp getnewsfeed.zip s3://hsfassih-todo-app/lambda/getnewsfeed.zip
                    aws s3 cp displaynews.zip s3://hsfassih-todo-app/lambda/displaynews.zip
                    aws s3 cp sendnews.zip s3://hsfassih-todo-app/lambda/sendnews.zip

            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                    terraform_version: "~1.5"

            -   name: Terraform Init
                working-directory: terraform
                run: terraform init
                
            -   name: Terraform apply
                working-directory: terraform
                run: |
                    terraform apply -auto-approve \
                    -var="bucket_name=hsfassih-todo-app" \
                    -var="lambda_source_hash=${{ steps.hashes.outputs.lambda }}" \
                    -var="getnewsfeed_source_hash=${{ steps.hashes.outputs.getnewsfeed }}" \
                    -var="displaynews_source_hash=${{ steps.hashes.outputs.displaynews }}" \
                    -var="sendnews_source_hash=${{ steps.hashes.outputs.sendnews }}" \
                    -var="ses_sender_email=${{ secrets.SES_SENDER_EMAIL }}" \
                    -var="environment=prod"

            -   name: Show Display News URL
                working-directory: terraform
                run: terraform output -raw displaynews_function_url