name: Deploy Lambda

on:
    push:
        branches: [main]
        paths:
            - "lambda/**"       # only when lambda code changes
            - "terraform/**"    # when terraform config changes

permissions:
    contents: read
    id-token: write     # required for OIDC auth (recommended over static keys)

jobs:
    deploy:
        name: Package & Deploy Lambda
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            # Authenticate to AWS with OIDC (instead of keys stored in secrets)
            -   name: Configure AWS credentials for OIDC
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
                    aws-region: us-east-1

            # Zip the contents of lambda/
            -   name: Package Lambda code
                run: |
                    cd lambda
                    zip -r ../function.zip .
                    cd ..

            # Compute hash for functions
            -   name: Compute source hash
                id: hash
                run: |
                    HASH=$(openssl dgst -sha256 -binary function.zip | openssl base64)
                    echo "value=$HASH" >> "$GITHUB_OUTPUT"

            # Upload the package to S3 bucket
            -   name: Upload zip to S3
                run: |
                    aws s3 cp function.zip s3://hsfassih-todo-app/lambda/function.zip

            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                    terraform_version: "~1.5"

            -   name: Terraform Init
                working-directory: terraform
                run: terraform init
                
            -   name: Terraform apply
                working-directory: terraform
                run: |
                    terraform apply -auto-approve \
                    -var="bucket_name=hsfassih-todo-app" \
                    -var="lambda_source_hash=${{ steps.hash.outputs.value }}" \
                    -var="environment=prod"